# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\xboxl\OneDrive\MoleConverter\moleConvert.ui'
#
# Created: Sun Oct 22 18:55:21 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(654, 405)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.amountEdit = QtGui.QLineEdit(self.centralwidget)
        self.amountEdit.setObjectName("amountEdit")
        self.horizontalLayout.addWidget(self.amountEdit)
        self.unitSel_1 = QtGui.QComboBox(self.centralwidget)
        self.unitSel_1.setObjectName("unitSel_1")
        self.unitSel_1.addItem("")
        self.unitSel_1.addItem("")
        self.unitSel_1.addItem("")
        self.unitSel_1.addItem("")
        self.horizontalLayout.addWidget(self.unitSel_1)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.formulaEdit = QtGui.QLineEdit(self.centralwidget)
        self.formulaEdit.setObjectName("formulaEdit")
        self.horizontalLayout_3.addWidget(self.formulaEdit)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.unitSel_2 = QtGui.QComboBox(self.centralwidget)
        self.unitSel_2.setObjectName("unitSel_2")
        self.unitSel_2.addItem("")
        self.unitSel_2.addItem("")
        self.unitSel_2.addItem("")
        self.unitSel_2.addItem("")
        self.horizontalLayout_2.addWidget(self.unitSel_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 200))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 654, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Convert", None, QtGui.QApplication.UnicodeUTF8))
        self.unitSel_1.setItemText(0, QtGui.QApplication.translate("MainWindow", "Grams", None, QtGui.QApplication.UnicodeUTF8))
        self.unitSel_1.setItemText(1, QtGui.QApplication.translate("MainWindow", "Moles", None, QtGui.QApplication.UnicodeUTF8))
        self.unitSel_1.setItemText(2, QtGui.QApplication.translate("MainWindow", "Molecules", None, QtGui.QApplication.UnicodeUTF8))
        self.unitSel_1.setItemText(3, QtGui.QApplication.translate("MainWindow", "Atoms", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "of", None, QtGui.QApplication.UnicodeUTF8))
        self.formulaEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Element / Formula", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "To", None, QtGui.QApplication.UnicodeUTF8))
        self.unitSel_2.setItemText(0, QtGui.QApplication.translate("MainWindow", "Grams", None, QtGui.QApplication.UnicodeUTF8))
        self.unitSel_2.setItemText(1, QtGui.QApplication.translate("MainWindow", "Moles", None, QtGui.QApplication.UnicodeUTF8))
        self.unitSel_2.setItemText(2, QtGui.QApplication.translate("MainWindow", "Molecules", None, QtGui.QApplication.UnicodeUTF8))
        self.unitSel_2.setItemText(3, QtGui.QApplication.translate("MainWindow", "Atoms", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Go", None, QtGui.QApplication.UnicodeUTF8))

